### ISSUE TITLE
getting trade history results in list with 0 elements

### ISSUE THREAD

**Issue by UniversalAE** [jandrews377/bitfinex-rest#1]
The code below results in an empty list, history.count = 0.   I'm trying to retrieve the trade history between the start and end.   Here I have limited the number of records to 120.   I think the problem is the override specifies start and end as type int.  In C# this defaults to int32.   The number to be passed is actually int64 and is not specified correctly in the Bitfinex API documentation.   UTC time codes are usually 1s resolution which would fit into an int32.   The Trades command in the API specifies 1mS resolution which only fits into an int64.   I have a working model of this command in C++ and have verified the documented 1mS resolution.

Your test suite does not test this method override.    In general the test suite does not test all method overrides and therefore the testing is not thorough.    I suggest a thorough test would have caught this problem.   A secondary issue is whether the list is empty as a result of an exchange error.  How do I catch the exchange error if an error is returned by the exchange?

These questions will become critical as you add authenticated commands to the package.   Errors like "not enough funds in the account" are critical to catch when making trades. 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Bitfinex;
using Bitfinex.Models;

namespace BitfinexV2RESTAPITest
{
	class Program
	{
		static void Main(string[] args)
		{
			List<ITrade> history = new List<ITrade>();
			var client = new BitfinexRestClient();

			history = client.GetTrades("tBTCUSD", 120, 1501105149000, 1501115149000);
			foreach (Bitfinex.Models.ITrade x1 in history.OrderBy(x1 => x1.MTS))
			{
				Console.WriteLine((x1.MTS).ToString() + " " + (x1.Price).ToString());
			}
		}
	}
}

```

**Comment by jandrews377** [comment]
First off, thanks for taking the time to report the issue. I have made the required code change on the 'release 1.0' branch. I am still working through getting the build pipeline to deploy the release branch to NuGet as a prerelease package. Stay tuned.

In regards to how exceptions are handled. If Bitfinex return an error, its exposed as a BitfinexException object:
`try
{
	var client = new BitfinexRestClient();
	var trades = client.GetTrades("BTCUSD", 120, 1501105149000, 1501115149000, SortDirection.NewestToOldest);
}
catch (BitfinexException ex)
{
	Console.WriteLine($"{ex.ErrorCode}: {ex.Message}", ex);
}`

**Comment by UniversalAE** [comment]
jandrews377, Have you made progress with the NuGet deployment?  I would prefer maintaining your updates through that medium.

**Comment by jandrews377** [comment]
Hi UniversalAE, apologies for the wait. New nuget package here https://www.nuget.org/packages/Bitfinex/0.1.16

**Comment by UniversalAE** [comment]
Thanks!!! I just got the Nuget update.  Tested and works.
