### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by sharibeads** [jandrews377/bitfinex-rest#5]
System.AggregateException : System.Exception: (10020) symbol: invalid

Sometimes there is an System.AggregateException
code:
            Bitfinex.BitfinexRestClient finex = new Bitfinex.BitfinexRestClient();
            Bitfinex.IBitfinexRestClient finex2 = new Bitfinex.BitfinexRestClient();
            string currency = "tETCBTC";
            List<Bitfinex.Models.IBook> abc = null;
            bool orderb = true;
            while (orderb)
            {
                orderb = false;
                try
                {
                    abc = finex.GetBooks(currency, Bitfinex.Models.Precision.P0);
                }
                catch (AggregateException e)
                {
                    Console.WriteLine(e.ToString());
                    orderb = true;
                }
            }

**Comment by jandrews377** [comment]
Hi sharibeads. Thanks for bringing this to my attention, I was missing some of the symbols. I have updated the list from the endpoint  https://api.bitfinex.com/v1/symbols.
I have released a new nuget package https://www.nuget.org/packages/Bitfinex/0.1.16
